#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/net/user/r1/unix/alles/projekte/genode/genode_start/genode-fx/trunk/EDK_projects/ml507/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = $(XILINX_EDK)
NON_CYG_XILINX_EDK_DIR = $(XILINX_EDK)

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex5

DEVICE = xc5vfx70tff1136-1

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp ../../ -lp ../../IP_cores/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MANAGE_FASTRT_OPTIONS = -reduce_fanout no

OBSERVE_PAR_OPTIONS = -error yes

DOPE_TEST_OUTPUT_DIR = dope_test
DOPE_TEST_OUTPUT = $(DOPE_TEST_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC440_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc440_0.elf

BRAMINIT_ELF_FILES =   $(PPC440_0_BOOTLOOP) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc440_0  $(PPC440_0_BOOTLOOP) 

ALL_USER_ELF_FILES = $(DOPE_TEST_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       ppc440_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec

LIBSCLEAN_TARGETS = ppc440_0_libsclean 

PROGRAMCLEAN_TARGETS = dope_test_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/ppc440_0_wrapper.ngc \
implementation/plb_v46_0_wrapper.ngc \
implementation/xps_bram_if_cntlr_1_wrapper.ngc \
implementation/xps_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/leds_8bit_wrapper.ngc \
implementation/leds_positions_wrapper.ngc \
implementation/push_buttons_5bit_wrapper.ngc \
implementation/dip_switches_8bit_wrapper.ngc \
implementation/iic_eeprom_wrapper.ngc \
implementation/sram_wrapper.ngc \
implementation/ethernet_mac_wrapper.ngc \
implementation/ddr2_sdram_wrapper.ngc \
implementation/sysace_compactflash_wrapper.ngc \
implementation/sram_util_bus_split_3_wrapper.ngc \
implementation/ddr2_sdram_util_bus_split_4_wrapper.ngc \
implementation/ddr2_sdram_util_bus_split_5_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/jtagppc_cntlr_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/plb_ps2_controller_0_wrapper.ngc \
implementation/plb_npi_vga_controller_0_wrapper.ngc \
implementation/xps_intc_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION DOPE_TEST
#################################################################

DOPE_TEST_SOURCES = ../../dope-embedded/test/test.c ../../dope-embedded/test/ml507/platform.c 

DOPE_TEST_HEADERS = ../../dope-embedded/include/dopedef.h ../../dope-embedded/include/dopelib.h ../../dope-embedded/include/keycodes.h ../../dope-embedded/include/vscreen.h ../../dope-embedded/test/platform.h 

DOPE_TEST_CC = powerpc-eabi-gcc
DOPE_TEST_CC_SIZE = powerpc-eabi-size
DOPE_TEST_CC_OPT = -O2
DOPE_TEST_CFLAGS = 
DOPE_TEST_CC_SEARCH = # -B
DOPE_TEST_LIBPATH = -L./ppc440_0/lib/   -L../../dope-embedded/lib/ml507/ 
DOPE_TEST_INCLUDES = -I./ppc440_0/include/  -I../../dope-embedded/include/ -I../../dope-embedded/test/ # -I
DOPE_TEST_LFLAGS =   -ldope 
DOPE_TEST_LINKER_SCRIPT = ../../dope-embedded/test/ml507/dope.ld
DOPE_TEST_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(DOPE_TEST_LINKER_SCRIPT) 
DOPE_TEST_CC_DEBUG_FLAG =  -g 
DOPE_TEST_CC_PROFILE_FLAG = # -pg
DOPE_TEST_CC_GLOBPTR_FLAG= # -msdata=eabi
DOPE_TEST_CC_INFERRED_FLAGS= -mcpu=440 
DOPE_TEST_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
DOPE_TEST_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
DOPE_TEST_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
DOPE_TEST_OTHER_CC_FLAGS= $(DOPE_TEST_CC_GLOBPTR_FLAG)  \
                  $(DOPE_TEST_CC_START_ADDR_FLAG) $(DOPE_TEST_CC_STACK_SIZE_FLAG) $(DOPE_TEST_CC_HEAP_SIZE_FLAG)  \
                  $(DOPE_TEST_CC_INFERRED_FLAGS)  \
                  $(DOPE_TEST_LINKER_SCRIPT_FLAG) $(DOPE_TEST_CC_DEBUG_FLAG) $(DOPE_TEST_CC_PROFILE_FLAG) 
